import { Gloock, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";

const fontHeading = Gloock({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "400",
});

const fontBody = Plus_Jakarta_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontHeading.variable} ${fontBody.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
